### PR TITLE
new tutorial for react

### PR DESCRIPTION
**Pull request by techiediaries**
Hi,

I'd like to contribute my tutorial to cdnjs

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@techiediaries thanks! Would you like to ask somebody help review and +1 your tutorial so that we can have more confidence to publish it? Many thanks :)

**Comment by techiediaries** [comment]
Sincerely i don't know anyone close who's experienced with React and Next.js. Is that necessary i wrote the tutorial from my own experience so be assured the steps i outlined are correct. Thanks!

**Comment by PeterDaveHello** [comment]
Hi @techiediaries, it's not very necessary, but as I don't use react, so it'll be better to have anyone who knows react to +1 on this. If we can't find anyone to help review it for days and if you have confidence on this, I can still merge it :)

**Comment by PeterDaveHello** [comment]
Is this tutorial for react or next.js or both?

**Comment by techiediaries** [comment]
@PeterDaveHello Next.js is a server side rendering framework for React apps so it's a React tutorial. Yes i have confidence on this tutorial because i tried the steps on my machine.

**Comment by PeterDaveHello** [comment]
Let's give it a try.

**Comment by PeterDaveHello** [comment]
@techiediaries it'll be great if you can setup a gravatar picture for your email techiediaries9@gmail.com, so we can have a author picture there.

**Comment by techiediaries** [comment]
@PeterDaveHello  Ok I will.

**Comment by PeterDaveHello** [comment]
@techiediaries nice, btw, I updated the twitter info, and adding GitHub, Facebook now, if you'd like to add your related info, feel free to send another PR please.

**Comment by techiediaries** [comment]
@PeterDaveHello Ok thanks!

**Pull request merged**
