### PR TITLE
Add animate.css getting started tutorial

### PR DESCRIPTION
**Pull request by Dog2puppy**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@Dog2puppy would you please leave `organizing-backbone-using-modules/tutorials.json` alone? Should have nothing to do with this PR, thanks!

**Comment by Dog2puppy** [comment]
@PeterDaveHello I was using that for my tutorials.json, but it ended up moving it instead of making a copy. I then recreated the file and put its contents in it.

**Comment by PeterDaveHello** [comment]
@Dog2puppy we need to leave unrelated files alone, if you need me to do that for you, please check the `Allow edits from maintainers.` checkbox at the right side, thanks.

**Comment by Dog2puppy** [comment]
It is checked.

**Comment by PeterDaveHello** [comment]
@Dog2puppy Need me to involve in the commits directly?

**Pull request merged**
